#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int nMotorSpeedSetting = 30;
float nPfactor = 0.3;
int grey = 50;
int lowest = 100;
int highest = 0;
void scanLine()
{
  motor[leftwheel] = 10;
  motor[rightwheel] = -10;
  time1[T1] = 0;
  while(time1[T1] < 500)
  {
    if (SensorValue[colour] > highest)
    {
      highest = SensorValue[colour];
    }
    if (SensorValue[colour] < lowest)
    {
      lowest = SensorValue[colour];
    }
  }
  grey = (highest - lowest) / 2;
  motor[leftwheel] = 0;
  motor[rightwheel] = 0;
}
 
task main()
{
  float error;
  scanLine();
  while (true)
  {
    error = SensorValue[colour] - grey;
    motor[leftwheel] = nMotorSpeedSetting - round(error * nPfactor);
    motor[rightwheel] = nMotorSpeedSetting + round(error * nPfactor);
    wait1Msec(50);
  }
}

Make sure you keep your eyes peeled as a public beta program will start very soon, once things like LCD and LED control have been added.  You can also follow a thread on the ROBOTC forums where the devs post what’s going on.  If you are keen to take part in the beta trials, make sure you buy yourself a 4GB SD card (or bigger), so you can run the special firmware.  I bought these class 10 cards very cheaply from DX.com.  I’ve really hammered them over the past few months and they’re holding up very nicely.

Stay tuned!
You may also like:
Good Things Come In Small Packages?
Mindstorms Power Scope
New Sleep Aid Takes CVS by Storm
PeakLife
Coming soon from Mindsensors: Light Sensor Array for NXT
How Older Men Are Increasing Testosterone
ForceFactor
New Fat Burner Takes GNC by Storm
ProbioSlim
Finding Bluetooth paired NXTs with WMI
The Dirty Little Secret Book Lovers Need to Know
The Book Insider

Tags EV3 Mindstorms ROBOTC robotc 4
 
Profile
Sign in with Twitter Sign in with Facebook
or

Name

EmailNot published

Website
CAPTCHA Image
Refresh Image

CAPTCHA Code*

Comment

Notify me of follow-up comments by email.

Notify me of new posts by email.
 
Author
Xander	

Infrastructure architect by day, and robotics enthusiast by night. Xander builds and programs robots and sensors. He is also one of the founders of the Mindboards forums. As a member of the LEGO MCP, he helps spread the word about the LEGO Mindstorms robotics platform.
 

    Pages
    Comments
    Popular
    Tags

    About Xander
    Botmag Article Companion Page
    ROBOTC Driver Suite
        Setting up the Driver Suite
    Support this Site

 
Get Social

    RSS Feed RSS FeedSubscribe
    ContactEmail Me
    TwitterFollow Me
    TumblrBot Bench
    FacebookBe a Fan!
    LinkedinConnect
    YouTubeMy Channel

 
 
Archives
